#ifndef INCLUDE_CONFIG_H
#define INCLUDE_CONFIG_H

#define CONFIG_DFL_MAP_NUM      1
#define CONFIG_DFL_REDUCE_NUM   1
#define CONFIG_DFL_STR_NUM      1
#define CONFIG_MIN_FILENAMES    10

#define CONFIG_DFL_MAP_DELIMS   ", \t\n"
#define CONFIG_DFL_MAP_VALUE    "1"

#define CONFIG_DFL_HASHTABLE_SIZE 1048577
#define CONFIG_DFL_HASH_SEED 257
#define CONFIG_DFL_HEAPTABLE_ROW 2048
#define CONFIG_DFL_HEAP_CHUNK_SIZE 1048577

#endif
